#!/bin/bash

jupyter contrib nbextension install --user
jupyter nbextension enable widgetsnbextension  --py --user
jupyter nbextension enable python-markdown/main  --py --user
jupyter nbextension enable hide_input/main
jupyter nbextension enable hide_input_all/main

jupyter-nbextension install rise --py --user
jupyter-nbextension enable rise  --py --user 

jupyter-nbextension install jupyter_wysiwyg --py --user
jupyter nbextension enable jupyter_wysiwyg  --py --user 

jupyter nbextension enable --py --sys-prefix ipyleaflet

#jupyter nbextension enable --py --sys-prefix jupyter_map_gl

#jupyter nbextension enable --py --sys-prefix gmaps

jupyter nbextension enable --py --sys-prefix bqplot

#jupyter serverextension enable --sys-prefix --py geonotebook
#jupyter nbextension enable --sys-prefix --py geonotebook

# Notebooks w/ extensions that auto-run code must be "trusted" to work the first time
jupyter trust index.ipynb
jupyter trust index_maps.ipynb
