#!/bin/bash

pip install ./magics

# Notebooks w/ extensions that auto-run code must be "trusted" to work the first time
jupyter trust index.ipynb
jupyter trust index_maps.ipynb
jupyter trust Projection_demo.ipynb

