#!/bin/bash

jupyter contrib nbextension install --user


jupyter-nbextension install rise --py --user
jupyter-nbextension enable rise  --py --user 

jupyter-nbextension install jupyter_wysiwyg --py --user
jupyter nbextension enable jupyter_wysiwyg  --py --user 

jupyter nbextension install --overwrite --py --user nbtutor
jupyter nbextension enable --py --user nbtutor

jupyter nbextension enable --py --sys-prefix ipyturtle

#Enable standard extensions
jupyter nbextension enable --py --sys-prefix widgetsnbextension
jupyter nbextension enable --py --sys-prefix python-markdown/main
jupyter nbextension enable --py --sys-prefix codefolding/main
jupyter nbextension enable --py --sys-prefix freeze/main
jupyter nbextension enable --py --sys-prefix varInspector/main
jupyter nbextension enable --py --sys-prefix python-markdown/main
jupyter nbextension enable --py --sys-prefix snippets_menu/main
jupyter nbextension enable --py --sys-prefix skip-traceback/main


# Notebooks w/ extensions that auto-run code must be "trusted" to work the first time
jupyter trust index.ipynb
jupyter trust index_computing.ipynb